### PR TITLE
Require Julia v1, use Project.toml instead of REQUIRE

### LINKED ISSUE #69: Problems installing HDF5 as test dependency due to Blosc
I'm having trouble with HDF5 as  a test dependency on Julia v1.3, due to Blosc nailing down Compat or something like that:

https://travis-ci.com/github/bat/BAT.jl/jobs/296129424

I don't quite see what's going on here, since the tests pass with Julia v1.4 - could it be because Blosc doesn't have a Project.toml yet?

### PR DESCRIPTION
**Pull request by oschulz**
Should fix #69

### CODE REVIEW

**Comment by stevengj** [comment]
You'll need to update the .travis.yml and appyveyor.yml files as well, so that it only tests with Julia 1.0 or later.

**Comment by oschulz** [comment]
Ooops, indeed - let's see if this works better.

**Comment by oschulz** [comment]
Is it Ok like this, @stevengj? I'm increasing the version to v0.6.0 in Project.toml, I hope that's all right?

**Comment by stevengj** [comment]
Thanks, LGTM!

**Pull request merged**
