### PR TITLE
Compat update for String rename

### PR DESCRIPTION
**Pull request by StefanKarpinski**

### CODE REVIEW

**Comment by yuyichao** [comment]
Missing import in test. (And I don't think we support using `ByteString` this way)

**Comment by tkelman** [comment]
Also missing minimum Compat version

**Comment by yuyichao** [comment]
(required version could be `0.7.15`)

Still has missing import in test and still have an incorrect use of `ByteString` in test (we don't support calling `ByteString` on an array I believe)

**Comment by timholy** [comment]
I think this can be closed.

**Pull request closed without merging**
