### PR TITLE
test on 0.5 too

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
"nightly" covered 0.5, but no longer. I'm not sure that is important (in general), 0.6 might cover accidental fault happening in 0.5 (or not...).

**Comment by stevengj** [comment]
Please don't skip ci in patches that affect testing.

**Comment by stevengj** [comment]
Can you open a new PR that doesn't skip CI, please?

**Comment by yuyichao** [comment]
Not needed anymore?

**Pull request closed without merging**
