### PR TITLE
bump to c-blosc 1.7, switch to bintray host...

### LINKED ISSUE #10: Building issues Win64
I am having trouble  adding package Blosc.jl on my 64bit Window7 system.  Once the process gets to INFO: Building Blosc, nothing seems to happen except the spinning indicator.  This used to work fine. I have recently reinstalled Julia and need to add back some of the packages.  I don't know if I have made other changes that could have impacted this package.  I ran across this problem trying to use MAT.jl.  Can you provide some advice on how to proceed?
Thank you.

### PR DESCRIPTION
**Pull request by stevengj**
This should close #10 by providing a signed https host for the binaries...

### CODE REVIEW

**Comment by stevengj** [comment]
Argh, only recent gcc versions support `-mavx2`.  I think I will have to disable the AVX support on Linux for now.

**Comment by tkelman** [comment]
Cool. You may want to shoot support@travis-ci.com an email asking to enable OSX support, they're accepting new requests right now. http://docs.travis-ci.com/user/multi-os/

**Comment by stevengj** [comment]
I just shot them an email.

**Comment by stevengj** [comment]
Okay, they say that multi-arch support is enabled, so hopefully the latest commit will run the tests on both OSX and Linux.

**Pull request merged**
